### ISSUE TITLE
System command failed

### ISSUE THREAD

**Issue by PeterGilles** [dopefishh/praatalign#1]
Hi,
I am trying to get aligner up and running. I did the necessary steps for the installation and when I try to align an interval, I get the following error in Praat:
![bildschirmfoto 2014-11-30 um 11 00 13](https://cloud.githubusercontent.com/assets/3244485/5237360/0e54cb02-7880-11e4-910e-edb089398e74.png)

As this error is rather unspecific, I have no clue what this could mean. Any help is appreciated.

Thanks
Peter

**Comment by lsy00** [comment]
After 8 years I encountered the same problem, and entering the full path doesn't seem to work for me - I don't even have the log file generated at the desired location even if I changed the "dev/null" path. What else can I do to make it work?
