### ISSUE TITLE
Can't find phonetizer file.

### ISSUE THREAD

**Issue by ems7** [dopefishh/praatalign#7]
When using the universal phonetizer I am unable to locate the phonetizer file. Could you tell me exactly which file it is looking for?

**Comment by dopefishh** [comment]
It is looking for a user-made universal phonetizer file. It can be any text file you created that represents the mapping from orthographic transcription to phonetic transcription.
In section 3.5.3(page 14) of the [manual](https://github.com/dopefishh/praatalign/releases/download/v1.9b/book_1.9.pdf) you can find a detailed explanation on how to create such files. If you have any more questions on this please drop a line.
