### ISSUE TITLE
Script crashes when trying to align files

### ISSUE THREAD

**Issue by ERSXS** [dopefishh/praatalign#8]
When trying to align any file, I get the following error message:

> Table "praat_temp_out": there is no column named "start".
>Script line 144 not performed or completed:
>« .current_start$ = Get value: .i, "start" »
>Script "C:\Users\Owner\Praat\plugin_pralign\aligntier.praat" not completed.
>Script "C:\Users\Owner\Praat\plugin_pralign\aligntier.praat" not completed.
>Menu command "" not completed.

I've attached all the the files that I've used and that have been generated [here](https://github.com/dopefishh/praatalign/files/545518/files.zip).

**Comment by dopefishh** [comment]
Thanks for the report. I'll be on this asap. Can you give some information about the setup.
Os, HTK, Sox and python version?

**Comment by dopefishh** [comment]
Dear ERSXS,
I can't reproduce your bug. For me it works. Attached is the aligned version of the TextGrid file. If you can please give the previously asked extra information.
[files2.zip](https://github.com/dopefishh/praatalign/files/545865/files2.zip)

**Comment by ERSXS** [comment]
Hey dopefishh,
That's so weird! And thanks for attaching the file. I'm running:
OS: Windows 10 Home
HTK: 3.4.1
sox: 14.4.2
Python: 3.5.2

**Comment by dopefishh** [comment]
praatalign doesn't work with `python3` yet. Please try with `python2`

**Comment by ERSXS** [comment]
I tried again using Python 2.7.12 and got the exact same error. Praat no longer unexpectedly quits on me when I try twice in a row, so that does seem to have helped.

On a hunch, I tried uninstalling and reinstalling both sox and htk, and it started working! I'm not sure what exactly the issue was, but thanks!
